name: Update TCG Prices

on:
  schedule:
    - cron: "0 */6 * * *"   # cada 6 horas
  workflow_dispatch:        # botón manual

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repo
        uses: actions/checkout@v3

      - name: Instalar Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Instalar dependencias
        run: pip install -r requirements.txt

      - name: Instalar Playwright
        run: |
          pip install playwright
          playwright install
          playwright install-deps

      - name: Ejecutar script
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
          SHEET_NAME: ${{ secrets.SHEET_NAME }}
          WORKSHEET_NAME: ${{ secrets.WORKSHEET_NAME }}
        run: python main.py